services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - ollama
    environment:
      - MONGO_URI=mongodb://mongo:27017/my-banker
      - OLLAMA_API=http://ollama:11434
      - JWT_SECRET=201fc9a67ef78be4d958f91bbad9f7d6c56ffdd923125b2e319318015474c130
      - INFURA_API_KEY=f49c060887b94c769b56624f4ef0ff38
      - ETHERSCAN_API_KEY=AB486YE7ED8U82X66GYU9KXEXKI9NXRTAZ
      - MORALIS_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6IjY5MjAxMzM4LWFkNGQtNGU5OS05ZmQwLTZhODU0Yzk4MTZhYSIsIm9yZ0lkIjoiNDUxMTI2IiwidXNlcklkIjoiNDY0MTcyIiwidHlwZUlkIjoiNGQ4ZTc2YzQtZGE2MC00MDc5LTllZGEtN2RmODM4ODAzZDAwIiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE3NDkxMjc2OTksImV4cCI6NDkwNDg4NzY5OX0.oJEOZkLNZxxND_pmWDio4mJEiLEo6jaABsAb7LvJV1c
      - COINMARKETCAP_API_KEY=f1df12ec-bed5-442d-879b-436f67548211
    volumes:
      - ./backend:/usr/src/app/backend
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    privileged: true

volumes:
  mongo-data:
  ollama-data:
